version: '3'

networks:
  nuxt:

services:
  # Development service
  development:
    image: node:latest
    container_name: development
    volumes:
      - ./:/var/www/nuxt
    working_dir: /var/www/nuxt
    command: >
      bash -c "node -v
      && yarn -v
      && yarn install
      && yarn lint
      && yarn run dev"
    ports:
      - "8011:8000"
    expose: 
      - "8011"
    networks:
      - nuxt
  
  # Production service
  production:
    image: node:latest
    container_name: production
    volumes:
      - ./:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    command: >
      bash -c "node -v
      && yarn -v
      && yarn install
      && yarn lint
      && yarn run build"
    networks:
      - nuxt

  # NGINX service
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: on-failure
    ports:
      - "8022:80"
    expose:
      - "8022"
    volumes:
      - ./:/usr/share/nginx/html
      - ./docker_services/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker_services/nginx/logs/access.log:/var/log/nginx/access.log
      - ./docker_services/nginx/logs/error.log:/var/log/nginx/error.log
    links:
      - production
    depends_on: 
      - production
    networks:
      - nuxt

 
